### ISSUE TITLE
gulp-compass is not working in the gulp's stream paradigm

### ISSUE THREAD

**Issue by lzl124631x** [appleboy/gulp-compass#124]
gulp-compass uses the config `css` and `scss` to determine the input files and output files, but a more-gulp way should be:
```
gulp.src('path/to/*.scss')
.pipe(compass({ /* settings other than input and output folder */)
.pipe(gulp.dest('path/to/.css')
```
I highly recommend gulp-compass change to this paradigm.

**Comment by lzl124631x** [comment]
I posted a question [here](http://stackoverflow.com/questions/35078782/how-to-put-the-file-compiled-by-gulp-compass-into-gulps-stream). @appleboy

**Comment by lzl124631x** [comment]
For `xx.scss`, there will be a `xx.css` generated by gulp-compass command. I don't want this file to be generated and prefer to output the `xx-what-ever-suffix.css` using `gulp.dest`. Is it possible to turn off the default `xx.css` file??

**Comment by alexandercastillo** [comment]
+1

**Comment by lzl124631x** [comment]
Came across another problem related -- I want to pass in argument (for example, `$cdn-domain`) that is different across staging and production setting. As `gulp-sass` doesn't support passing in argument inherently, I have to do preprocessing using `gulp-replace` or `gulp-preprocess` to change the setting in sass file. However, since `gulp-compass` doesn't read the upper-stream, you cannot do any preprocessing. Anyway, you can do postprocessing, but it's ugly, IMHO.

```
gulp.src('src/sass/*.scss')
        .pipe(replace(/CDN_DOMAIN/g, 'https://cdn.xxx.com')) <--- preprocessing here, but doesn't work
        .pipe(compass({
            css: 'src/css',
            sass: 'src/sass'
        }))
        <-- have to put the processing here. ugly...
        .pipe(cssnano())
        .pipe(gulp.dest('dist/css'));
```

**Comment by oroszlanyzsolt** [comment]
I got the following error runing a gulp projet today. I can confirm that removing gulp-compass dependency the gulp project runs just fine but with compass I get the following error:

```internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:873:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at module.exports (\node_modules\gulp-compass\lib\compass.js:149:15)
    at DestroyableTransform.compile [as _flush] (\node_modules\gulp-compass\lib\index.js:60:5)
    at DestroyableTransform.<anonymous> (\node_modules\gulp-compass\node_modules\through2node_modules\readable-stream\lib\_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at finishMaybe (\node_modules\gulp-compass\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)```
