### ISSUE TITLE
Error in plugin 'gulp-compass'

### ISSUE THREAD

**Issue by guoyoujin** [appleboy/gulp-compass#130]
hello,
I use this bag when the following error message
`````
Starting 'dev-config'...
[14:54:24] Starting 'scripts'...
[14:54:24] Starting 'inject_sass'...
[14:54:24] gulp-inject 6 files into index.scss.
[14:54:24] Finished 'dev-config' after 318 ms
[14:54:24] Finished 'inject_sass' after 179 ms
[14:54:24] Starting 'styles:compass'...
[14:54:24] /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:91:in `expand_path': Insecure operation - expand_path (SecurityError)
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:91:in `extension_dir'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:46:in `gem_build_complete_path'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/stub_specification.rb:144:in `missing_extensions?'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1037:in `block in find_by_path'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1036:in `each'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1036:in `find'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1036:in `find_by_path'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems.rb:189:in `try_activate'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Users/guoyoujin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/guoyoujin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:9:in `<main>'

[14:54:25] Error in plugin 'gulp-compass'
Message:
    Compass failed
[14:54:25] all files 34.03 kB
[14:54:25] Finished 'scripts' after 821 ms
`````

**Comment by dvanadio** [comment]
no one to help you bro? 
I'm having the same issue here. (legacy project)
