### ISSUE TITLE
Gulp-compass compressing sass not working

### ISSUE THREAD

**Issue by avinvarghese** [appleboy/gulp-compass#71]
Running **Sass 3.4.3**, **Compass 1.0.1**, **Gulp 3.8.8** and **Gulp-compass 1.3.1**

```
var gulp = require('gulp');
var compass = require('gulp-compass');
var gutil = require('gulp-util');

 gulp.task('compass', function() {
        gulp.src('comp/sass/style.scss')
            .pipe(compass({
                sass: 'comp/sass',
                image: 'dev/theme/images',
                style: 'compressed'
            })
            .on('error', gutil.log))
            .pipe(gulp.dest('dev/theme/css'))
    });
```

compass Task is compiling the sass but compression is not working. It output a normal uncompressed css file.

**Comment by koenpeters** [comment]
I tried it with sass 3.4.13, compass 1.0.3 and gulp-compass 2.0.3 and I have the same issue. I read on [stackoverflow](http://stackoverflow.com/questions/25808128/gulp-compass-compressing-sass-not-working) that this issue might have a workaround by including a separate config.rb file, but that didn't work for me unfortunately. Any news on this issue?

**Comment by appleboy** [comment]
@koenpeters Do you provide detail of gulp compass config?

**Comment by appleboy** [comment]
and I will try sass 3.4.13, compass 1.0.3 and gulp-compass 2.0.3 again.

**Comment by koenpeters** [comment]
This is what I used:

    gulp.task('compass', function() {
      return gulp.src(compass_src)
          .pipe(plumber()) /* catches the errors so the process doesn't crash on watch*/
          .pipe(compass({
                  style: 'compressed',
                  image: './web/global/images',
                  css: './web/global/css',
                  sass: './web/_dev/sass',
                  debug: true,
                  sourcemap: true
          }))
          .pipe(combineMediaQueries({ log: true }))
          .pipe(gulp.dest(compass_dst));
});

Is this what you wanted to see?

**Comment by koenpeters** [comment]
Hi @appleboy, 

Have you had the chance to take a look? I can't seem to figure it out. ':/

**Comment by appleboy** [comment]
Hi @koenpeters 

I will take it. Give me more time. Thanks.

**Comment by koenpeters** [comment]
Okay, Thanks a bunch!

**Comment by stasgavrylov** [comment]
Same problem here with Sass - 3.4.13, Compass - 1.1.0.alpha.3, gulp-compass - 2.0.3 and Gulp - 3.8.11

**Comment by Durdona** [comment]
Hello there, 

I am having the same issue now ... Can someone tried how to fix it ?

**Comment by Durdona** [comment]
Here is what I am using 
 "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-browserify": "^0.5.1",
    "gulp-coffee": "^2.3.1",
    "gulp-compass": "^2.1.0",
    "gulp-concat": "^2.5.2",
    "gulp-util": "^3.0.4",
    "jquery": "^2.1.4",
    "mustache": "^2.0.0"
  }

**Comment by webactiv** [comment]
Hello,

I'm having the same issue. If anyone finds a solution please let me know :)

Stephen

**Comment by grantorin** [comment]
Similar problems
<pre>
gulp.task('compass', function() {
  gulp.src(path.src.sass)
    .pipe(compass({
      config_file: config.rb,
      css: path.src.css,
      sass: path.src.sass,
      image: path.src.img,
      comments: true,
      style: expanded // line 66
    }))
    .pipe(gulp.dest(path.src.css))
    .pipe(browserSync.stream());
});
</pre>

console writes:
<pre>
[13:51:55] 'compass' errored after 25 ms
[13:51:55] ReferenceError: expanded is not defined
    at Gulp.<anonymous> (D:\OpenServer\domains\test\testProject\gulpfile.js:66:14)
    at module.exports (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at Gulp.<anonymous> (D:\OpenServer\domains\test\testProject\node_modules\gulp\index.js:36:18)
    at Gaze.<anonymous> (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\index.js:18:14)
    at Gaze.emit (events.js:110:17)
    at Gaze.emit (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:129:32)
    at D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:415:16
[13:51:56] Starting 'compass'...
[13:51:56] 'compass' errored after 7.28 ms
[13:51:56] ReferenceError: expanded is not defined
    at Gulp.<anonymous> (D:\OpenServer\domains\test\testProject\gulpfile.js:66:14)
    at module.exports (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at Gulp.<anonymous> (D:\OpenServer\domains\test\testProject\node_modules\gulp\index.js:36:18)
    at Gaze.<anonymous> (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\index.js:18:14)
    at Gaze.emit (events.js:110:17)
    at Gaze.emit (D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:129:32)
    at D:\OpenServer\domains\test\testProject\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:415:16
</pre>
....
sass -v 3.4.15
compass -v 1.0.3
"gulp": "^3.9.0"

**Comment by michelecocuccio** [comment]
Hello. 
Same issue here. Anyone was able to solve it?

**Comment by lowtrux** [comment]
Hi, i'm having the same issue here, Here's what i'm using :

   "devDependencies": {
    "browser-sync": "^2.11.1",
    "browserify": "^13.0.0",
    "gulp": "^3.9.1",
    "gulp-browserify": "^0.5.1",
    "gulp-compass": "^2.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-connect": "^3.1.0",
    "gulp-connect-php": "0.0.7",
    "gulp-if": "^2.0.0",
    "gulp-jquery": "^1.1.2",
    "gulp-jshint": "^2.0.0",
    "gulp-sass": "^2.2.0",
    "gulp-util": "^3.0.7",
    "jshint": "^2.9.1"
  }

Any chance somebody can help with this ? Many Thanks !

**Comment by plus20charisma** [comment]
I had the same issue and I used rvm to change my ruby version to 2.3.0 and reinstalled compass @ 2.3.0.  That seemed to fix the problem.

**Comment by kaluki** [comment]
Hello,

I had the same issue until I added @import "compass" to my root scss file.

**Comment by alikarimii** [comment]
hi 
i create two config.rb file whit different name and save in project folder 
**config.rb**   >> output_style = :expanded
**configC.rb** >> output_style = :compressed


**in gulpfile:**
`
var env,
    scssSources,
    jsSources,
    htmlSources,
    outputDir,
    sS;

env = process.env.NODE_ENV || 'development';

if(env==='development') {
    outputDir = 'builds/development/';
    sS = 'config.rb'
}else {
    outputDir = 'builds/production/';
    sS = 'configC.rb'
}
gulp.task('compass', function(){
    
    gulp.src(scssSources)
    .pipe(compass({
        config_file: sS,
        sass: 'components/sass',
        image: outputDir + 'images',
    }))
        .on('error', gutil.log)
    .pipe(gulp.dest(outputDir + 'css'))
    .pipe(connect.reload())
});`

and run gulp. issue solved.

**Comment by 5argon** [comment]
@kaluki Thanks, previously my project had `@import "compass/css3"` and it worked. Now it does not work because of the `/css3` bit.

**Comment by internationalhouseofdonald** [comment]
Is this still an issue? Is there maybe a plugin that could substitute for gulp-compass like gulp-clean-css?

**Comment by imgnx** [comment]
::FIXED::

So, using `style: 'compressed'` doesn't work and `MinifyCSS` is no longer a working package. That's what's causing all of this confusion.
I ended up fixing this issue by using a config.rb file.

Here is what I tried:
```
gulp.task('compass', function() {
	gulp.src(sassSources)
		.pipe(compass({
			sass: 'components/sass',
			image: outputDir + 'images',
			style: sassStyle
		})
		.on('error', gutil.log))
		.pipe(gulp.dest(outputDir + 'css'))
		.pipe(connect.reload())
});
```

Here is how my code looks in gulpfile.js now:
```
gulp.task('compass', function() {
	gulp.src(sassSources)
		.pipe(compass({
			config_file: './config.rb',
			css: 'components/css',
			sass: 'components/sass'
			// image: outputDir + 'images',
			// style: sassStyle
		})
		.on('error', gutil.log))
		.pipe(gulp.dest(outputDir + 'css'))
		.pipe(connect.reload())
});
```

Here is my config.rb file:
```
preferred_syntax = :sass
http_path = '/'
css_dir = 'components/css'
sass_dir = 'components/sass'
images_dir = 'components/images'
javascripts_dir = 'components/scripts'
relative_assets = true
line_comments = true
output_style = :compressed
```

And here's where I got the solution from: https://gist.github.com/nathansmith/1179395

**Comment by randy-emu** [comment]
@internationalhouseofdonald having the "output_style = :compressed" in the config.rb does compress the css. Thank you for this solution. However, it would be nice to have it in the gulpfile.js directly.

**Comment by K-JAX** [comment]
@randy-emu I agree. Here's a not-so-great solution that would work until somebody smarter than me comes along :)

Create "expanded-config.rb"

```
preferred_syntax = :sass
http_path = '/'
javascripts_dir = 'components/scripts'
relative_assets = true
line_comments = true
output_style = :expanded
```


Create "compressed-config.rb"
```
preferred_syntax = :sass
http_path = '/'
sass_dir = 'components/sass'
images_dir = 'components/images'
javascripts_dir = 'components/scripts'
relative_assets = true
line_comments = true
output_style = :compressed
```

Then in your gulpfile.js, create some conditional logic

```
var env = process.env.NODE_ENV || 'development';

if (env==='development') {
	outputDir = 'builds/development/';
	sassConfigStyle = 'expanded';
}	else {
	outputDir = 'builds/production/';
	sassConfigStyle = 'compressed';
}
```
... gulpfile.js compass task

```
gulp.task('compass', function() {
	gulp.src(sassSources)
		.pipe(compass({
			config_file: 'components/sass/'+ sassConfigStyle +'-config.rb',
			css: outputDir + 'css',
			sass: 'components/sass',
			image: outputDir + 'images',
		}))
		.on('error', gutil.log)
		.pipe(gulp.dest(outputDir + 'css'))
		.pipe(connect.reload())
});
```
And that works for me. But, please note that for some reason with this method, you can't overwrite the output style of the previously output css file. So you'll have to delete the file and re-output. Otherwise it seems to be a temporary solution :)
